### PR TITLE
[WIP] Several new features

### PR DESCRIPTION
**Pull request by samuelgarcia**
Do not merge for now.

Several features:
  * Save raw file in tridesclous less memory agressive.
  * laucher save run time for each sroter/recording in csv

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : I would like to change a bit the BaseSorter.

As you known, I would like to have a static method to read result from forlder.
So we could open result from intermediate folder after a long run.

Ideally, it would be a staticmethod like this
```python
sorting_KL = KilosortSorter.read_from_folder('my_output_folder_KL')
sorting_TDC = TridesclousSorter.read_from_folder('my_output_folder_TDC')
```
I need to patch the MS4 as you known.

I also need a change in kilosort, circus and klusta.
These sorter have "file_name" that is the name of the internal name inside the folder.
By default it is recording for all of then.
My guess is that this file_name is not set because it do not matter at all because each sorting is always done in separte directories.

This "file_name" for this sorter (kilosort, circus and klusta) is also a instance attribute done in **_setup_recording** and so it is needed for **_get_one_result**

To implement the staticmethod **read_from_folder** I need to get rid of this file_name.

Is it possible to remove it and to generate always the deault one ("recording") ?

**Comment by alejoe91** [comment]
@samuelgarcia 
Yes I think we can get rid of file_name and use `recording` by default. Then output folder will be the only thing we need.

Regarding MS4 I think an easy fix would be to change:
`self._sorting_result[ind] = sorting`

to

`se.MdaSortingExtractor.writeSorting(sorting, str(output_folder / 'firings.mda'))`

then the _get_one_result will become:
```
    def _get_one_result(self, recording, output_folder):
        sorting = se.MdaSortingExtractor.(str(output_folder / 'firings.mda'))
        return sorting
```

This should make it compatible with the class organization and allow the read from folder. Right?

**Comment by samuelgarcia** [comment]
Cool. I will do.
For MS4, it was the plan already.

**Comment by samuelgarcia** [comment]
@alejoe91:
My week will be very busy. I won't have time to work more on this.
You should merge this because it change a bit the class BaseSorter.

I will be back on launcher next week.

I think you will have to make some changes in KS2.

**Comment by alejoe91** [comment]
I'll test it first and the n merge. I have to check if it breaks our code and make the changes in case

Alessio

**Comment by samuelgarcia** [comment]
Of course.

**Pull request merged**
