### PR TITLE
New default parameters for next release

### PR DESCRIPTION
**Pull request by mhhennig**
Now performs scaling and bandpass by default as this is required in almost all cases. This can be turned off for Biocam data for a slight speed increase.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Have you seen error on travais about numpy.quantile ?

**Comment by mhhennig** [comment]
I'm trying to fix, it is the numpy version. I don;t understand though why Travis fails now.

**Comment by alejoe91** [comment]
Sometimes hs fails.. don't know why. You can trigger the build it again from travis

**Comment by mhhennig** [comment]
I just replicated the test locally, with the same packages, and cannot find the reason it fails. Help please :(
One thought, is the test data generated randomly, with a different seed each time? Is it possible it fails as it cannot detect any units? Can anyone point me to where this is done?

**Comment by colehurwitz** [comment]
I can try to help! I’ll go onto the branch and try soon

**Comment by samuelgarcia** [comment]
One travis is passing and the other is wrong.

I think we can merge this. it is only parameters.

**Comment by mhhennig** [comment]
Oh, passing. Can we fix a random seed for the test data, I think this will solve this?

**Comment by colehurwitz** [comment]
I tried to fix the random seeds, but maybe I missed some! Would be good to fix all of them

**Comment by samuelgarcia** [comment]
Do we more random else where than toy example ?

**Comment by colehurwitz** [comment]
Let's merge? I can't find any other randomization

**Comment by alejoe91** [comment]
yes it passes :)

**Pull request merged**
