### PR TITLE
fix export to phy

### PR DESCRIPTION
**Pull request by colehurwitz31**

### CODE REVIEW

**Comment by alejoe91** [comment]
Did you find errors in the other PR? Otherwise that's the intended behavior and you can close this :)

**Comment by colehurwitz31** [comment]
I found an error with it. It was saying that templates is a list so it doesn't have shape

**Comment by colehurwitz31** [comment]
So the notebook kept failing

**Comment by alejoe91** [comment]
Ok, but that's not a fix ;)

Try to substitute the if with:

if not isinstance(templates, list):

If more units, templates should be a list

**Comment by colehurwitz31** [comment]
Hmm, I guess I am not sure what templates is... I thought it was just a list. What else can it be?

**Comment by alejoe91** [comment]
Array

**Pull request merged**
