### PR TITLE
fix local CAR

### PR DESCRIPTION
**Pull request by MarineChap**
- add assert when the selecting annulus does not contain channels
- fix verbose option bug

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi @MarineChap .
Do you think this is something that have to be propagated here  https://github.com/SpikeInterface/spikeinterface/tree/big_refactoring ?

**Comment by MarineChap** [comment]
Hi @samuelgarcia 
Yes, the assert in case of wrong radius parameters;  not containing any channel references.

**Comment by MarineChap** [comment]
Also, good to know for you and to add somewhere in the doc (?), after test with the neuropixels, the values equivalent to what catgt is using (aka (2,8) electrodes site) for their own local car (which was the main way to do this filtering type with neuropixels before implementating it here) is **(30,55)**.

**Comment by samuelgarcia** [comment]
Do you think you would have time to make a similar PR on the new API ?

**Comment by MarineChap** [comment]
Yes, I can do that this morning.

**Comment by alejoe91** [comment]
Thanks @MarineChap 

Is it good to go for merging?

**Comment by MarineChap** [comment]
Yes. Thanks.

**Comment by alejoe91** [comment]
Actually, before we merge can you set `local_radius` to (30, 55) as you suggested? I think that (2, 8) is unrealistic and it will fail for almost all probes

**Comment by MarineChap** [comment]
yes of course. That makes sense.

**Comment by alejoe91** [comment]
> @samuelgarcia I should change the default value for the new api too ?

Yes please!

**Comment by alejoe91** [comment]
@MarineChap  can you change it in the function as well: https://github.com/SpikeInterface/spiketoolkit/blob/121ce5ddb9f85f16b2c87937b7e82d62fe2d8198/spiketoolkit/preprocessing/common_reference.py#L139?

**Comment by MarineChap** [comment]
Oups sorry! I amended my commit.

**Pull request merged**
