### PR TITLE
Exposed all objects for GUI

### PR DESCRIPTION
**Pull request by colehurwitz31**
Exposed all objects for GUI

### CODE REVIEW

**Comment by colehurwitz31** [comment]
This allows the GUI to get the preprocessing classes from spiketoolkit rather than just the functions. Also, I removed some asterisks from preprocessing that forced keywords.. they were annoying. If you want me to put them back, then I will, but I think they are unnecessary.

**Comment by colehurwitz31** [comment]
It is ready to be merged whenever

**Comment by samuelgarcia** [comment]
Hi @colehurwitz31 .
If I anderstand correctly you force keywaord argument anywhere in this PR to make the GUI easier.

Don't you plan to in add some attribute directly in tookit to describe gui_params ?

Like:

```python
class BandpassFilterRecording:
  _gui_parms = [
        {'name':'freq_min', 'value': 300., 'type':'float'},
        {'name':'freq_max', 'value': 6000., 'type':'float'},
    ...
    ]
    def __init__(...):
         ...
```

**Comment by colehurwitz31** [comment]
I don’t actually force keyword arguments anywhere. I removed the asterisks that force keyword arguments. The only changes I made here other than that is exposing the objects.

Yes, I plan to add GUI params soon, but I ran into a bug with the the PyQtGraph Parameter library that I was trying to solve first where default values are not working as intended. I am also planning on implementing extractor_list, preprocessing_list, and posprocessing_list similar to sortinglist.

**Comment by samuelgarcia** [comment]
OK sorry.
I read this too fastly.

**Comment by samuelgarcia** [comment]
This is OK for me.

My only concern is that you made some pep8 modification on launcher and BaseSorter since I am working on this in #73 I hope that I won't have conflict.

**Comment by colehurwitz31** [comment]
I actually don’t think I really changed anything in those two modules (all the spaces I deleted, I added back) So I don’t think there will be any conflicts, but I am not sure. I probably shouldn’t have added them to the commit.

**Comment by samuelgarcia** [comment]
No worry, we will see git shoudl be able to merge this :)

**Pull request merged**
