### PR TITLE
Some other change about the compute_misclassification option.

### PR DESCRIPTION
**Pull request by samuelgarcia**
* label > compute_label
  * template_txt_performance depend on self._compute_misclassification
  * compute_misclassification=True for GroundTruthSoringComparison.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : I really don't like the **label** (now rename **compute_label**). option.
label must be compute anyway for any method in this class.

We remove it some times ago, Ithink we where agrre on this and now it appear again.
What is the use case of compute_label=False ?

compute_misclassification=False I understand totally, this is for SF.

@magland : Important note : I put back **compute_misclassification=True** by default in ST.
I think I prefer ST to be exhaustive by default.
So you have to explicitly compute_misclassification=False in SF code for speedup.

@alejoe91 @magland @colehurwitz @mhhennig  This must be discussed, does default params have to match SF so user can run code and have same results immediatly ?
Or can ST have more option (and longer to compute) for comparison ?

**Comment by colehurwitz** [comment]
I think it is ok to have default params be different in ST than in SF and they can change the defaults to match SF

**Comment by alejoe91** [comment]
Can you call it compute_labels?

**Comment by samuelgarcia** [comment]
Yes of course but first tell me the usecase of the kargs :)

**Comment by alejoe91** [comment]
Compute_labels can be set to false in the sortingcomparison, as only the matching is needed

**Comment by alejoe91** [comment]
Compute_misclassification is set to False in SF :)

**Comment by samuelgarcia** [comment]
OK point for you.
Done already.

**Comment by samuelgarcia** [comment]
Merge when you want.

**Pull request merged**
