### PR TITLE
refactoring names in postprocessing and quality metrics

### PR DESCRIPTION
**Pull request by colehurwitz**
@alejoe91 @samuelgarcia Is this a sensible default value?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I would say 300 per units is enough.
Even 100 estimate correctly the median.
1000 spike per 1000 channel per 100 sample is already a lot of memory for one unit.

**Comment by colehurwitz** [comment]
I just realized that:

max_num_waveforms is per unit
max_num_pca_waveforms is per recording

They should not be equal.

**Comment by colehurwitz** [comment]
I changed to 

300 waveforms per unit, 10000 waveforms for pca

**Comment by alejoe91** [comment]
:+1: keep this open for the moment! I'll try to improve the get_amplitude_performance

**Comment by colehurwitz** [comment]
This won't work without some modifications. Currently, setting max_num_waveforms to anything but infinity will throw an error.

**Comment by colehurwitz** [comment]
can I change:

max_num_waveforms --> max_num_spikes_per_unit
max_num_pca_waveforms --> max_num_spikes_pca

**Comment by colehurwitz** [comment]
Ok, so I made a lot of name changes:

max_num_waveforms -> max_spikes_per_unit
max_num_pca_waveforms -> max_spikes_for_pca
max_snr_waveforms -> max_spikes_per_unit_for_snr
max_spikes_for_unit -> max_spikes_per_cluster

**Comment by samuelgarcia** [comment]
Hi Cole I don't follow so much the discussion and long investigatioin about that.
Sorry.

Why '*_per_units** and then **_per_cluster** ?

I would have done :
  * max_spikes_for_unit -> max_spikes_per_unit
also.

I would have by default everything XXXX_per_unit=300, no ?
Why 1000 make phy less buggy ?

**Comment by alejoe91** [comment]
@colehurwitz this can be fixed. I can't do it right now but let's keep this open. We just need to update indexing and to forse the export to phy to compute all wf

**Comment by colehurwitz** [comment]
@samuelgarcia the metrics have a **per_cluster** parameter so I made the name match that.

**Comment by colehurwitz** [comment]
@alejoe91 do you want to fix in this pull request or a new one?

**Comment by alejoe91** [comment]
Looks good! :)

**Comment by colehurwitz** [comment]
Should we merge this and then you will open a new PR for memory stuff?

**Comment by alejoe91** [comment]
Yep

**Pull request merged**
