### PR TITLE
Change logic to avoid to force .dat for binary

### PR DESCRIPTION
**Pull request by samuelgarcia**
In actual implementation a binary file for klusta MUST be ".dat" now it is can be any extention (.raw, .bin)

### CODE REVIEW

**Comment by colehurwitz** [comment]
That is a nice change!

**Comment by samuelgarcia** [comment]
I thought it was simple but travis is unhappy...

**Comment by samuelgarcia** [comment]
I fix it.
But finally klusta really need a file with .dat extension.
This restriction is really annoying.
I propose to merge and I will be back on this soon.

**Comment by alejoe91** [comment]
should we rename this https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extraction_tools.py#L224 
`write_binary_file` (dropping the dat) accordingly?

**Comment by samuelgarcia** [comment]
Not not merge, there is sttill a bug.

**Comment by samuelgarcia** [comment]
Yes I think we could rename this function.
dat is not official at all many format use raw or bin.

klusta working only with dat is really a pain.

**Comment by samuelgarcia** [comment]
Finally there is no bug. i merge this.

**Pull request merged**
