### PR TITLE
Added tests and parallel amplitude calculation

### PR DESCRIPTION
**Pull request by alejoe91**
https://github.com/SpikeInterface/spiketoolkit/issues/366

@llobetv  Can you test if this speeds up your processing? you can call export_t0_phy with the `n_jobs` argument (and that applies to waveforms and amplitudes).

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I don't understand why it is so complicated.
Waveforms are not extracted yet for otehr stuff like PCA before that ?

**Comment by llobetv** [comment]
Now export PCA is optional so waveform are sometimes not all extracted, to improve export_to_phy duration.

**Comment by llobetv** [comment]
I'm stuck with this error and I dont find anything about it...
Do you know where it comes from?

>   File "/home/llobet/miniconda3/lib/python3.7/site-packages/spiketoolkit-0.6.3-py3.7.egg/spiketoolkit/postprocessing/postprocessing_tools.py", line 208, in get_unit_waveforms
>     output_list = Parallel(n_jobs=n_jobs, backend=joblib_backend)(
> 
>   File "/home/llobet/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 684, in __init__
>     % (backend, sorted(BACKENDS.keys())))
> 
> ValueError: Invalid backend: 4, expected one of ['loky', 'multiprocessing', 'sequential', 'threading']

**Comment by alejoe91** [comment]
I'll double check that, one sec :)

**Comment by alejoe91** [comment]
ok I had the wrong param. Should be fixed now!

**Comment by llobetv** [comment]
After testing it improve a lot the duration,  930s to 350s with 8 cores with compute_pc_features False.
Duration is 20s with both compute_pc_features and compute_amplitudes False

**Pull request merged**
