### PR TITLE
typos and indentation

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Very good job :)

(How can you find time for typos checking ???)

**Comment by alejoe91** [comment]
the build is actually passing https://travis-ci.org/SpikeInterface/spiketoolkit/builds/545110935

**Comment by colehurwitz** [comment]
Do you use an IDE Alessio?

**Comment by colehurwitz** [comment]
Nice work!

**Comment by alejoe91** [comment]
yes I use pycharm. but I did this changes manually

**Pull request merged**
