### PR TITLE
Problem in FilterRecording

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This shoud fix a bug intriduce with previous PR and fix something in whiten

**Comment by colehurwitz** [comment]
Great! This is a nice change.

**Comment by alejoe91** [comment]
Awesome!

**Comment by samuelgarcia** [comment]
@alejoe91 the 2 solution are exacttly the same.

**Comment by samuelgarcia** [comment]
I propose to merge because it prevent doc from building.

**Comment by alejoe91** [comment]
Ok let's keep svd then

**Pull request merged**
