### PR TITLE
updated spiketoolkit for shared functions

### PR DESCRIPTION
**Pull request by colehurwitz**

### CODE REVIEW

**Comment by colehurwitz** [comment]
I will disable matplotlib functionality in spikeglx as it isn't used

**Comment by samuelgarcia** [comment]
All example should be remove from here they are replaced by spikeinterface/examples

**Comment by samuelgarcia** [comment]
Same here.

**Comment by colehurwitz** [comment]
Do examples need to be removed from all repos? My pull request doesn't cover this. Maybe you can make an issue?

**Comment by samuelgarcia** [comment]
I think yes.
@alejoe91 ?

The good thing with example in spikeinterface is that they are generated (and centralized).

**Comment by colehurwitz** [comment]
Removed them all

**Pull request merged**
