### PR TITLE
[WIP] First step for tridesclous integration.

### PR DESCRIPTION
**Pull request by samuelgarcia**
This is the very first step for tridesclous integration.

I also need to write ```TridesclousSortingExtractor``` in spikeextractor.

### CODE REVIEW

**Comment by alejoe91** [comment]
Cool! I will test it in the weekend on the toy example and merge it then :)

Alessio

**Comment by samuelgarcia** [comment]
HI @alejoe91.
Do not merge it too soon.
I will make some improvement.

A major concern is that trisdesclous is fast when opencl is activated.
At the moment it is not the case it use numpy backend and not CL kernel.

**Comment by samuelgarcia** [comment]
Hi all.
For me this is ready to merge.
If you are happy with could merge it ? So I could start porting sorters to classes in another branch.

I main difficulty I have for now is that the parmeters higly depend on the dataset itself (nb_chan, geometry, probe density, sampling rate, ...)

When classes done I will be able to enhance a bit more this sorter to make more automatic parameters.

Note that the travis bug is not due to this PR.

**Comment by colehurwitz31** [comment]
Merged

**Pull request merged**
