### PR TITLE
Added docstrings

### PR DESCRIPTION
**Pull request by alejoe91**
- preprocessing
- postprocessing
- validation

will finish comparison before merging

### CODE REVIEW

**Comment by alejoe91** [comment]
also removed curation folder

**Comment by colehurwitz31** [comment]
Looks great! This will be super helpful for the GUI and for using these tools.

Could we rename q --> quality_factor? I think that would be a good change.

**Comment by alejoe91** [comment]
in scipy it's called q, but I guess being clearer won't harm :)

**Comment by colehurwitz31** [comment]
Hmm... I guess it may not be a big deal then. Up to you :)

**Comment by alejoe91** [comment]
I will merge this and we can improve docstrings later on :)

**Pull request merged**
