### PR TITLE
 Change logic to avoid to force .dat for binary

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
idelaly I would like to merge this before the release.

**Comment by colehurwitz** [comment]
Sounds good. Btw, Alessio and I are adding sampling frequencies to current SortingExtractors. What do you recommend for formats that don't have that information?

I was thinking an optional sampling_frequency argument can be added to those sorting extractors like:
MDASortingExtractor(firings, sampling_frequency=None)

**Comment by samuelgarcia** [comment]
I think it is better to have explicitly self._sampling_frequency = None for theses format.

The only consequence is that the user will have to provide manually for SpikeComparison otherwise it will raire an error.

**Comment by samuelgarcia** [comment]
This is a very small change I merge it.

**Pull request merged**
