### PR TITLE
(WIP) Test files

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by colehurwitz** [comment]
Looks good. :) Should we just add to this pull request over time?

**Comment by alejoe91** [comment]
Yep!

**Comment by alejoe91** [comment]
@colehurwitz Could you make the missing test for the `normalize_by_quantile`? or @martinosorb ?
I don't understand how it should work properly.

**Comment by colehurwitz** [comment]
It would be best if @martinosorb or @mhhennig did it as I don't understand how it works either.

**Comment by alejoe91** [comment]
Hei @colehurwitz I would merge this. 
Only `test_normalize_by_quantile` in preprocessing and `test_compute_pca` are missing. For the latter, we can create fake waveforms starting from gaussians in the PC space. This approach could be used also for spikemetrics.

**Pull request merged**
