### PR TITLE
First example of post processing module based off of CuratedSorting

### PR DESCRIPTION
**Pull request by colehurwitz31**
Hoping to get some feedback on this class. I wanted it to be similar to the filterrecording structure where each postprocessing module is a class based off of the CuratedSortingExtractor.

@alejoe91 @samuelgarcia

### CODE REVIEW

**Comment by alejoe91** [comment]
Hi Cole!

It looks good to me but I would change the naming as I think it can be a bit confusing.

**Comment by colehurwitz31** [comment]
I want to have threshold in the name so that they know that it will get rid of units below that threshold. I can think about a better name that still contains threshold though

**Comment by colehurwitz31** [comment]
How does that look?

**Comment by colehurwitz31** [comment]
Got a weird travis error:

KeyError: "Unable to open object (object 'clusters' doesn't exist)"

In the Klusta test suite... Have you seen this before?

@alejoe91 @samuelgarcia

**Comment by colehurwitz31** [comment]
Ready to merge when you are @alejoe91

**Pull request merged**
