### PR TITLE
Update postprocessing.py

### PR DESCRIPTION
**Pull request by llobetv**
Correction for #360 
Change template exctraction for grouping_property, now if some template are missing to reach the right number of channel, it's fill with 0, and channel idx with -1.
Change compute_template_similarity to avoid using these channels.

### CODE REVIEW

**Comment by llobetv** [comment]
I try with NaN but for teamplate phy crash, and for channel idx, it was change to abherant negative value somewhere in the code.

**Comment by llobetv** [comment]
Here to test:

```
import pytest
import spikeextractors as se
from spiketoolkit.postprocessing import export_to_phy
import os
import shutil
from spiketoolkit.preprocessing import remove_bad_channels

@pytest.mark.implemented
def test_export_to_phy():
    folder = 'test'
    if os.path.isdir(folder):
        shutil.rmtree(folder)
    rec, sort = se.example_datasets.toy_example(dump_folder=folder, dumpable=True, duration=10, num_channels=8)
    rec.set_channel_groups([0, 0, 0, 0, 1, 1, 1, 1])
    rec = remove_bad_channels(rec, [1,2, 5])    
    export_to_phy(rec, sort, output_folder='phy_group', grouping_property='group', recompute_info=True)



if __name__ == '__main__':
    # test_waveforms()
    test_export_to_phy()
```

**Comment by llobetv** [comment]
An exemple:
image
image

**Comment by alejoe91** [comment]
@llobetv testing it now and it looks good :)

**Comment by alejoe91** [comment]
It sounds a bit strange that with -1 it works, because -1 is the last index, but maybe this is built-in in phy to discard channels eith -1

**Pull request merged**
