### PR TITLE
Enhance environ path for KS, KS2 and IronClust

### PR DESCRIPTION
**Pull request by samuelgarcia**
Enhance environ path for KS, KS2 and IronClust

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This PR help for environement path for KS, KS, IronClust:
  * modify the class attr **installed**
  * check in params when the path is present
  * put the path with os.environement

**Comment by alejoe91** [comment]
ok great

**Comment by alejoe91** [comment]
so if I pass the path to `run_kilosort2` it saves it as os variable? does it work on Windows as well?

**Comment by samuelgarcia** [comment]
Not tested on windows. Nor really tested on linux but the logic was quite not good because installed was not updated and params not checked on this.

**Comment by samuelgarcia** [comment]
I think we can merge.
Thing like that
```os.environ["IRONCLUST_PATH"] = ironclust_path```
 will not be persistent but at least during the python run we have a consistent path between class attr and the local env.

**Comment by alejoe91** [comment]
ok

**Pull request merged**
