### PR TITLE
Proper names on confusion matrix and option to turn off count text.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by colehurwitz** [comment]
I noticed that the confusion matrices were quite hard to read. Will this fix that?

**Comment by samuelgarcia** [comment]
It remove text optionally usefull for big matrices.
I am unlucky with travis.
I hung on hs. My guess is that there is compilation imcompatibility somewhere.
Is HS compiled on travis ?

**Comment by alejoe91** [comment]
it looks fine on travis
I suggest we merge :)

**Comment by samuelgarcia** [comment]
It is because I relaunch it.
We now have some random fail (hung) at hs steop. My guess is compilation problem.

**Pull request merged**
