### PR TITLE
Study

### PR DESCRIPTION
**Pull request by samuelgarcia**
Start of independant study submodule.
Done in a class now but keep functions too.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Feel free to resolve the conflict back to what you have on your side... I am having a weird bug with spiketoolkit where it can't find the sorterlist in the spikesorter module..

**Comment by colehurwitz** [comment]
Sorry, accidentally closed the pull request (misclick).

**Comment by samuelgarcia** [comment]
I think this is ready for review.
It is first step.

The main idea is to have a class for gtstudy.

I will go back on this with more feature later on:
  * optional compute of SNR and make it persistent
  * some automatic plots

When this PR will be merged I will change spikeresults to use this new class.

@alejoe91 @colehurwitz @magland @mhhennig : would you be OK to mention spikeresults on the readme ?

**Comment by colehurwitz** [comment]
Yes, that is a good idea. Would you like to add a section to the README?

**Comment by samuelgarcia** [comment]
I think yes but very short and that would mention spikeresults as axemple of use.

**Comment by alejoe91** [comment]
@samuelgarcia double check that my conflict resolution was correct. I think so :)

**Comment by samuelgarcia** [comment]
@alejoe91 : I don't anderstand what you did.
The line that appear in the commit already where in my code, no ?

**Comment by alejoe91** [comment]
Yes but when I megred the other PR there was a conflict with master

**Comment by samuelgarcia** [comment]
OK.

**Comment by alejoe91** [comment]
@samuelgarcia  merge?

**Comment by samuelgarcia** [comment]
Yep. Please do.

**Pull request merged**
