### PR TITLE
Fix for pre_scaling function call.

### PR DESCRIPTION
**Pull request by mhhennig**
Name of the function was changed, and not implemented here.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Do you plan a release very soon ?

**Comment by colehurwitz** [comment]
It would be good to make a release soon since it affects spikeforest

**Comment by mhhennig** [comment]
We made a release, but then people kept pushing to master, so the release is not in sync. This is why I increased the minor version number. Pypi needs this one. From now on, we should keep development separate, maybe a dev branch.

**Comment by colehurwitz** [comment]
I think he is asking if we should make a release for spiketoolkit so spikeforest can get this change

**Comment by samuelgarcia** [comment]
@mhhennig : I don't follow you, sorry. Wich relase do you mention : 0.3.0 done by alessio ?
I don't see more relase on pypi.

I don't think we need a official dev branch, it slow down everything for merging.
In my mind dev branch are in our git, when new PRt work they AND validated by others, we merge immadiatly. 

And if one software is block by a pypi release of spiektoolkit wa can relase whenever we want.

**Comment by samuelgarcia** [comment]
For release, it is also good to play with miletones of github to see what is urgent or not.

**Comment by alejoe91** [comment]
I don't see 0.3.1 neither. Only 0.3.0 has been released. In order to make a release you have to tag a commit and push tags. We should discuss about releases, but I think it's ok to fix bugs in PR and merge to master as soon as they pass.

**Comment by colehurwitz** [comment]
I think the concern is that although the version on github says 0.3.0, we made a bunch of changes that make it different that PyPi version 0.3.0. Should we increment the version on github to show that?

**Comment by mhhennig** [comment]
Sorry, I just changed setup.py. @alejoe91, are you ok to merge and tag and release?

**Comment by alejoe91** [comment]
Yes but we should tag 0.3.1 first. You can merge to master, then git tag 0.3.1and got push --tags from master

**Pull request merged**
