### PR TITLE
Tridesclous

### PR DESCRIPTION
**Pull request by samuelgarcia**
I am working on parameters for tridesclous sorter.
DO NOT MERGE NOW because this is depend on tridesclous==1.2.0 that will be release this week.

The main change is parameters name to make less ambiguous units (second vs sample vs ms).

After this could it be possible to make a release of spiketoolkit soon, so I could be able to propagate changes in spikeforest wrapper.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Ready to be reviewe and merged.

This is mainly for:
 * cleaning parameters names in tridesclous an dmake less ambiguous units.
 * change nested dict in tridesclous easily

It is based on tridesclous==1.2.0 rlease some hours ago.

**Comment by colehurwitz** [comment]
Great! Looks good

**Comment by colehurwitz** [comment]
Since it is sorter specific, I don’t have much to say :)

**Comment by samuelgarcia** [comment]
OK merging so.

**Pull request merged**
