### PR TITLE
Same changes as in SpikeForest

### PR DESCRIPTION
**Pull request by yger**
I copied the changes submitted to SpikeForest, in order for the two repos to be in sync. Note that current version of SC is now 0.8.0, available with pip/conda/docker. These changes are not meant to turn the code into a pure automatic software. They are just slightly decreasing the number of clusters, and further investigation should be performed to turn it into a pure automatic workflow.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Great! Thanks for propagating the changes over to spiketoolkit. I think this can be merged as it passes all tests, right @samuelgarcia @alejoe91 ?

**Comment by alejoe91** [comment]
@yger Thank you for the changes! Merging :)

**Comment by samuelgarcia** [comment]
@yger : what you can also do to avoid to change code and params in 2 places is to change the spikeforest wrapper on top on the spiketoolkit wrapper.

I did this for tridesclous (and @colehurwitz did the same for heardingspike2), so now I only need to change params in spiketoolkit + change version in spikeforest which is more simple.
Have a look of tridesclous wrapper in SF.

Pierre : we did some comparisons which we will present t next Tuesday in Edimburgh.
Unfortunatly it was done with previous version of SC. So results should be not as good as with this version.
Nervertheless, the presentation is not about comparing sorter but to show how easy you can do it with spiketoolkit.

**Comment by yger** [comment]
Ok, I'll have a look. @samuelgarcia Comparison on what? Performances, speed, as in SpikeForest? If performances, with greedy merges or not? As said, I really think a global framework to compare sorters is a great idea, and I'll try to be more involved, but putting numbers is hard, since every sorters have somehow hidden assumptions.

**Comment by samuelgarcia** [comment]
We try to put several numbers.
That is the topic.

No greedy merge, we do comparison on raw output.

**Pull request merged**
