### PR TITLE
Use spikesorters package for sorters

### PR DESCRIPTION
**Pull request by alejoe91**
Remove all sorters and import `spikesorters` module in sorters submodule.

@samuelgarcia @magland @colehurwitz  should we add a hard dependency on spikesorters at this point?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : what do you call hard depency ?
Is it with a ficed version or not ?

I think yes we must have in setup a dependency on 'spikesorters' but without version.

You fogot to add the dependency in travis. I think.

**Comment by alejoe91** [comment]
@samuelgarcia 

The tests here will be only for preprocessing (TODO), comparison, study, postprocessing (TODO), and validation (TODO).

Removing all the spike sorting specific installations from the travis

**Comment by alejoe91** [comment]
So spikesorters is up and running. This is up and running too. Can I merge? @samuelgarcia @colehurwitz

**Comment by colehurwitz** [comment]
If it works, I am good to merge!

**Pull request merged**
