### PR TITLE
Make explicit loops when n_jobs=-1 to avoid pickle errors

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
See #108

**Comment by samuelgarcia** [comment]
@colehurwitz31 @alejoe91 : is it OK to merge this ?

**Comment by colehurwitz31** [comment]
Er, could you answer the review question first about n_jobs being -1 or 1

**Comment by samuelgarcia** [comment]
I hevn't see th review question. 
I think you have to finalize the review or simply to make comment without full review process.

**Comment by colehurwitz31** [comment]
Sorry about that. Submitted the review

**Comment by samuelgarcia** [comment]
Oups sorry.
I was unaware of this -1.
I thought it was for  **not parralelism**.
We should definitivelly put n_job==1 by default.

We should include this in test.

I propose to remove what I have done but put n_job=1 everywhere.

**Comment by colehurwitz31** [comment]
That works for me.

**Comment by samuelgarcia** [comment]
I still put **match_spikes** outside to avoid closure problem with pickle.

**Comment by samuelgarcia** [comment]
Done + tests.

**Comment by colehurwitz31** [comment]
Excellent. When it passes, I think you can merge

**Comment by samuelgarcia** [comment]
OK merging. So.

**Pull request merged**
