### PR TITLE
Revenge of the Snake Case

### PR DESCRIPTION
**Pull request by colehurwitz31**

### CODE REVIEW

**Comment by colehurwitz31** [comment]
Close to being refactored! The only failing test is the mountainsort test because I think it is locally using an older version of spikeextractor. @magland Can you update ms4 to work with spikeextractors 0.4.0?

**Comment by samuelgarcia** [comment]
Amazing work.
Waouh.
the travis is more complaining about a "getChannelIds". Is it the problem ?

**Comment by alejoe91** [comment]
@samuelgarcia yes ms4 uses internally spikeextractors, so we need to update it. I can try to do it tomorrow in my fork and send a PR to @magland

**Comment by samuelgarcia** [comment]
OK.
I think they should do a tag/release in MS4 before the case transition and then include the patch.

**Pull request merged**
