### PR TITLE
postprocessing fixes

### PR DESCRIPTION
**Pull request by alejoe91**
some cleaning and fixes to postprocessing module

### CODE REVIEW

**Comment by colehurwitz** [comment]
What 'property' values does extract_property_from_maximum_channel support?

Can you list the available properties in the docstring?

**Comment by alejoe91** [comment]
it's any channel property :) in general it would be group

**Comment by colehurwitz** [comment]
Right, but channel properties are finite so not any string they put in will work. Off the top of my head, we have 'group', 'location'... etc.

**Comment by colehurwitz** [comment]
Wait, I think I am misunderstanding the function

**Comment by colehurwitz** [comment]
What does this function do?

**Comment by alejoe91** [comment]
they are not finite. One can load any channel property.

So what it does is to extract the property from the channel with the largest peak and save the same property as sorting property

**Comment by colehurwitz** [comment]
Sorry, so what channel properties would you want to store as unit properties?

**Comment by alejoe91** [comment]
'group', 'brain_area', whatever really :)

**Comment by alejoe91** [comment]
e.g. say you have group information, but you don't spike sort by group. Then this function can be used to assign each unit to the right group ;)

**Comment by colehurwitz** [comment]
Could we potentially change the name? I think extract_property_from_maximum_channel doesn't really give an idea of what it does.

Maybe something like: 
```
set_units_properties_by_max_channels_properties
```

 or something?

**Comment by colehurwitz** [comment]
Also, I think  get_unit_template --> get_units_templates since it is multiple units.

**Comment by colehurwitz** [comment]
And  get_unit_max_channel --> get_units_max_channels

**Comment by colehurwitz** [comment]
Also, maybe compute_pca_scores --> comput_unit_pca_scores

**Comment by alejoe91** [comment]
You can go ahead and make the changes :) all this functions are also used by other functions + notebooks + docs

**Comment by colehurwitz** [comment]
Ok, I will change all of those

**Comment by colehurwitz** [comment]
You can merge this first

**Comment by colehurwitz** [comment]
I just think the current names don't match the intended use and will confuse people who are unfamiliar with the functions (e.g. me).

**Comment by alejoe91** [comment]
I think though it should be unit_templates etc. Not units

**Comment by alejoe91** [comment]
Similar to get_channel_groups, not channels_groups

**Comment by colehurwitz** [comment]
I think it has to be singular or plural based on what it does. So get_units_templates is more accurate to what the function does.

**Comment by alejoe91** [comment]
It can return a single template as it takes the unit_ids arg. I would prefer get_unit_...s notation.

**Pull request merged**
