### PR TITLE
flat dictionary for hs

### PR DESCRIPTION
**Pull request by martinosorb**
Cf. #68. I went for fully flat here, which is perhaps a bit confusing to the user who doesn't know what needs to be tweaked, but I suppose that's more of a problem of HS rather than spiketoolkit.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This look good.
Do you plan to include filtering capability in HS2 in this PR ?
Or is it ready to merge ?

**Comment by martinosorb** [comment]
I don't know about the filtering, I'll need to ask Cole and Matthias.

**Comment by alejoe91** [comment]
You can check how it's implemented in mountainsort4. I think it's a great addition and the default could be False

**Comment by alejoe91** [comment]
@martinosorb I'll merge this and we can make a new PR for the filter

**Pull request merged**
