### PR TITLE
sortingcomponents module

### PR DESCRIPTION
**Pull request by alejoe91**
Added sortingtools module with `detect_spikes` function

https://github.com/SpikeInterface/spikesorters/issues/75

### CODE REVIEW

**Comment by alejoe91** [comment]
@magland @samuelgarcia @colehurwitz something like this?

**Comment by colehurwitz** [comment]
Looks about right! Maybe we can call the module `sortingcomponents` and then have files like: `sortingcomponents/detection.py`, `sortingcomponents/clustering.py`, etc. Since we may add more.

**Comment by alejoe91** [comment]
@colehurwitz better?

**Comment by colehurwitz** [comment]
Yep!! Nice work. This is a cool addition.

**Comment by alejoe91** [comment]
Can I merge this?

**Comment by samuelgarcia** [comment]
OK for me.
I like the place where it is implmenented!






 (and don't like so much the idea of detecting spikes independently by channel. But it is a good start)

**Pull request merged**
