### PR TITLE
Put back test_launcher.py

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 @colehurwitz 

I have a travis fail because of
```
    from spikeextractors import CurationSortingExtractor
E   ImportError: cannot import name 'CurationSortingExtractor'
```
Have propagated change of CurationSortingExtractor into ST ?

**Comment by alejoe91** [comment]
@colehurwitz 

You should merge SE and ST PRs at the same time. We have to wait for the other PR

**Comment by colehurwitz** [comment]
Whoops, that is my fault. Not sure why I merged the spikeextractors change

**Comment by colehurwitz** [comment]
I will fix shortly

**Comment by colehurwitz** [comment]
I am just running to into issues with spike sorters..

**Comment by colehurwitz** [comment]
Alright, curation is now part of spiketoolkit. If you merge with master, it should fix your issues @samuelgarcia . Sorry again for not pushing both changes simultaneously

**Comment by samuelgarcia** [comment]
Thank you no worry no hurry.

**Pull request merged**
