### PR TITLE
Start proting Yass in spiketoolkit from spikeforest.

### PR DESCRIPTION
**Pull request by samuelgarcia**
I plan to implement yass sorter.
THe work is not done yet just started to settle thing.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@magland : I have started to implement YassSorter in spiketoolkit form the code of spikeforest.
Could you have a look  and test it ?
As I never used yass I not sur to make correctly.

**Comment by samuelgarcia** [comment]
At the moment I have this error:
```
NotImplementedError: Only .csv and .prb probe files can be saved.
```


I guess that you have saveProbeFile is a forked version inside spikeforest rather that the one in spikeextractor.
I will have a look.

**Comment by alejoe91** [comment]
@samuelgarcia

For the probe file at the moment only prb and CSV files are supported. I think we should extend the saveProbeFile to dump npy arrays as required by yass.
Could you do that?

**Comment by samuelgarcia** [comment]
They already did the extention in spikeforest fork of spikeextractors.

I need to also port this.

**Comment by samuelgarcia** [comment]
@magland 

I port the code form spikeforest to spiketoolkit.

It is almost done but I have a bug in yass.
Is seams to be related to parameters. Many kargs are missing.

I copy/paste config.yaml from spikeforest, does this work with a particular version of yass ?


```
2019-03-13 21:12:38.281251: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1795945000 Hz

2019-03-13 21:12:38.281889: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x1a41100 executing computations on platform Host. Devices:

2019-03-13 21:12:38.281957: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>

Traceback (most recent call last):

  File "/home/samuel/.virtualenvs/py36/bin/yass", line 11, in <module>

    sys.exit(cli())

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/click/core.py", line 764, in __call__

    return self.main(*args, **kwargs)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/click/core.py", line 717, in main

    rv = self.invoke(ctx)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/click/core.py", line 1137, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/click/core.py", line 956, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/click/core.py", line 555, in invoke

    return callback(*args, **kwargs)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/command_line.py", line 57, in sort

    output_dir=output_dir, complete=complete)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/command_line.py", line 66, in _run_pipeline

    pipeline.run(config, logger_level, clean, output_dir, complete)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/pipeline.py", line 75, in run

    set_config(config)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/__init__.py", line 67, in set_config

    CONFIG = Config.from_yaml(config)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/config/config.py", line 28, in from_yaml

    obj = cls(mapping)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/config/config.py", line 104, in __init__

    mapping = validate(mapping)

  File "/home/samuel/.virtualenvs/py36/lib/python3.6/site-packages/yass/config/validate.py", line 46, in validate

    .format(validator.errors))

ValueError: Errors occurred while validating the configuration file: {'deconvolution': [{'lam': ['unknown field'], 'rank': ['unknown field'], 'threshold': ['unknown field']}], 'neural_network_autoencoder': ['unknown field'], 'neural_network_detector': ['unknown field'], 'neural_network_triage': ['unknown field'], 'preprocess': [{'filter': ['must be of dict type'], 'templates_partial_data': ['unknown field'], 'whiten_batchwise': ['unknown field']}], 'recordings': [{'order': ['required field']}], 'spikes': ['unknown field']}

Traceback (most recent call last):
  File "test_yass.py", line 16, in <module>
    YassCommonTestSuite().test_on_toy()
  File "/home/samuel/Documents/projet/SpikeInterface/spiketoolkit/spiketoolkit/sorters/tests/common_tests.py", line 24, in test_on_toy
    sorter.run()
  File "/home/samuel/Documents/projet/SpikeInterface/spiketoolkit/spiketoolkit/sorters/basesorter.py", line 87, in run
    self._run(recording, self.output_folders[i])
  File "/home/samuel/Documents/projet/SpikeInterface/spiketoolkit/spiketoolkit/sorters/yass/yass.py", line 74, in _run
    raise Exception('yass returned a non-zero exit code')
Exception: yass returned a non-zero exit code
```

**Comment by jamesjun** [comment]
If you like, you may refer to our implantation in SpikeForest. The superclass is different but it may be easy to change. 

-James

**Comment by samuelgarcia** [comment]
I made the code directly from your class but with some simplification due to the new BaseSorter.

I think that this new code work more or less:
  * copy raw signal
  * make probe file
  * make the config.yaml

But the "yass" command fail because of missing kargs.

The code you do
```yass /path/toconfig.yaml```
from a fresh yass installed I need to do
```yass sort /path/toconfig.yaml```

Is it the correct way ?
Could have you a short look ?

Just run the test from my branch and you will see:
spiketoolkit/sorter/tests/test_yass.py

**Comment by alejoe91** [comment]
Hi @samuelgarcia 

I tried this but it fails for some problems in the config file. Have you tried this out? I think that the newest version uses a different config file (https://github.com/paninski-lab/yass/blob/master/examples/config_sample_complete.yaml).

When I added the preprocess and detect step from that file it ran.

**Comment by samuelgarcia** [comment]
Outch this new config file quite big.


@jamesjun: did you implement the new version with this big new config.yml in spikeforest ?

**Comment by alejoe91** [comment]
@samuelgarcia I asked the YASS group to make a PR to spikesorters (https://github.com/paninski-lab/yass/issues/288)

Can we drop this?

**Pull request closed without merging**
