### PR TITLE
fix epochs

### PR DESCRIPTION
**Pull request by colehurwitz**
Setting all the infinities to None

### CODE REVIEW

**Comment by colehurwitz** [comment]
Should work with the spikeextractors pull request

**Comment by samuelgarcia** [comment]
Hi COle,

Here I see some copy/paste and so I would make a function like this one:

```python
def get_in_epoch_bool_mask(spike_times, epoch):
    start_frame = epoch[1]
    end_frame = epoch[2]
    if start_frame is None:
        start_frame = 0
    if end_frame is None:
        end_frame = np.inf
    in_epoch = (spike_times>=start_frame) & (spike_times<=end_frame)
    return in_epoch
```

Also for limits I would use >= for low limit and < for high limit, no ?

**Comment by colehurwitz** [comment]
Yes, I will make a function for this. I agree about the less than logic, but I need to check josh’s code to see which one he did.

**Comment by samuelgarcia** [comment]
Perfect :)

**Comment by colehurwitz** [comment]
Thanks for the suggestion! I will keep an eye out for redundant code in the future.

**Comment by colehurwitz** [comment]
Should we release spikeextractors so that this will pass? @alejoe91

**Pull request merged**
