### PR TITLE
Minor modifications for SC 0.8.4

### PR DESCRIPTION
**Pull request by yger**
Mostly cosmetic modifications for the parameter file of SC, slightly simplified for 0.8.4 (just released via pip/conda)

### CODE REVIEW

**Comment by colehurwitz** [comment]
Hi @yger , just to update, we have moved all spike sorting related code to [spikesorters](https://github.com/SpikeInterface/spikesorters). If you could make the pull request there, that would be great.

**Comment by yger** [comment]
Sure, sorry for that, will do it asap

**Comment by colehurwitz** [comment]
No worries! We split spiketoolkit into --> spiketoolkit, spikesorters, spikecomparison. So we did a lot of changes relatively recently.

**Comment by yger** [comment]
Is this spikesorters project used by spikeforest, or should I also push the slight reformatting of the parameter there too?

**Comment by alejoe91** [comment]
@yger yes spikesorters is used! We'll make sure changes are correctly propagated to spikeforest :)

**Comment by samuelgarcia** [comment]
@pierre : to to be sure to propagate change to SF  you need also to make a PR in spikeforest so that the docker file have the good version for both spykingcircus and spikesorters.

**Pull request closed without merging**
