### PR TITLE
fix snr when recording is short

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by colehurwitz** [comment]
Isn't this addressed in the if and else statement below your change?

**Comment by alejoe91** [comment]
no it fails!

**Comment by alejoe91** [comment]
ahhhh
sorry I missed it!!!! you are right, it's probably somewhere else..sorry!

**Comment by colehurwitz** [comment]
Maybe don't merge until we discuss a little for some of these metric things

**Comment by alejoe91** [comment]
I see, it's here: 
`randint(0, recording.get_num_frames() - n_frames)`

we are trying to fix the build in the docs. We'll release a 0.5 when it's fixed

**Comment by alejoe91** [comment]
I think it shuld be: `n_frames >= recording.get_num_frames():` instead of `n_frames > recording.get_num_frames():`

**Comment by alejoe91** [comment]
exactly, it fails when the duration is exactly the same. Will revert the changes and make a new PR

**Pull request merged**
