### PR TITLE
exposed all parameters in threshold_snr

### PR DESCRIPTION
**Pull request by Shawn-Guo-CN**
To fix issue #252

### CODE REVIEW

**Comment by colehurwitz** [comment]
If you could update the GUI params, that would be great as well.

**Comment by colehurwitz** [comment]
Although, the GUI cannot use a metric_calculator parameter.

**Comment by Shawn-Guo-CN** [comment]
> Although, the GUI cannot use a metric_calculator parameter.

Thanks for this, man. Next commit is coming.

**Comment by colehurwitz** [comment]
Hey Shawn, so we are refactoring some of the quality metric stuff (which will affect this PR). So I will wait to merge this.

**Comment by colehurwitz** [comment]
Looks good. All done?

**Comment by Shawn-Guo-CN** [comment]
> Looks good. All done?

Not yet, I'm updating the comments for function *threshold_snr*. 2 mins.

**Comment by Shawn-Guo-CN** [comment]
Now, this PR is ready.

**Pull request merged**
